export * from "./generated/api";
export * from "./generated/api.schemas";
export { setBaseUrl, setAuthTokenGetter } from "./custom-fetch";
export {
  abandonInterviewSession,
  getGetDashboardSummaryQueryKey,
  getGetJobQueryKey,
  getGetMeQueryKey,
  getGetRoadmapQueryKey,
  getGetSkillBreakdownQueryKey,
  getGetUpcomingTasksQueryKey,
  getGetWeeklyProgressQueryKey,
  getListInterviewsQueryKey,
  getListCrtQuestionsQueryKey,
  getListJobsQueryKey,
  getListProgressQueryKey,
  useCreateInterview,
  useCreateJob,
  useDeleteJob,
  useAnalyzeResume,
  useGetDashboardSummary,
  useGetJob,
  useGetMe,
  useGetRoadmap,
  useGetSkillBreakdown,
  useGetUpcomingTasks,
  useGetWeeklyProgress,
  useListInterviews,
  useListCrtQuestions,
  useListJobs,
  useSubmitCrtAnswers,
  useSubmitAnswer,
  useUpdateProgress,
} from "./local-api";
